#!/bin/bash

###################################################################
## Patch-ShellSkript                                             ##
##                                                               ##
## Autor: XXX                                                    ##
## Datum: XXX                                                    ##
##                                                               ##
## Inhalt: Aufruf von apt_autopatch.sh per curl                  ##
##                                                               ##
## Ablage unter /usr/local/bin + chmod 755                       ##
## Anschließend von überall ausführbar mit "update"              ##
###################################################################

#Prüfen ob SuperUser, ansonsten Wechsel und Beginn des Skript von vorne
[ `whoami` = root ] || { sudo "$0" "$@"; exit $?; }
echo --- Wechsel auf Superuser erfolgt. ---
sleep 1
clear
#Remotezugriff per curl auf das zentrale apt_autopatch.sh Skript
#curl muss ggf. auf den Systemen nachinstalliert werden
bash -c "$(curl -fsSL <PATH_TO_apt_autopatch.sh_HTTP_HTTPS>)"
